zk:
  image: bobrik/zookeeper
  net: host
  ports:
   - 2181:2181
  environment:
    ZK_CONFIG: tickTime=2000,initLimit=10,syncLimit=5,maxClientCnxns=128,forceSync=no,clientPort=2181
    ZK_ID: 1

master:
  image: mesosphere/mesos-master:0.25.0-0.2.70.ubuntu1404
  net: host
  environment:
    MESOS_ZK: zk://192.168.99.100:2181/mesos
    MESOS_QUORUM: 1
    MESOS_CLUSTER: docker-compose
    MESOS_WORK_DIR: /var/lib/mesos

slave:
  build: .
  net: host
  environment:
    MESOS_MASTER: zk://192.168.99.100:2181/mesos
    MESOS_CONTAINERIZERS: docker,mesos
    MESOS_PORT: 5051
    MESOS_RESOURCES: ports(*):[11000-12999];mem(*):5000;cpus(*):2
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /usr/local/bin/docker:/usr/bin/docker
    - /var/run/docker.sock:/var/run/docker.sock

#slave-two:
#  image: mesosphere/mesos-slave:0.25.0-0.2.70.ubuntu1404
#  net: host
#  name: slavetwo
#  environment:
#    MESOS_MASTER: zk://192.168.99.100:2181/mesos
#    MESOS_CONTAINERIZERS: docker,mesos
#    MESOS_PORT: 5052
#    MESOS_RESOURCES: ports(*):[12000-12999];mem(*):5000;cpus(*):2
#  volumes:
#    - /sys/fs/cgroup:/sys/fs/cgroup
#    - /usr/local/bin/docker:/usr/bin/docker
#    - /var/run/docker.sock:/var/run/docker.sock

marathon:
  image: mesosphere/marathon:v0.11.0
  net: host
  environment:
    MARATHON_MASTER: zk://192.168.99.100:2181/mesos
    MARATHON_DECLINE_OFFER_DURATION: 3600000
